In [1]:
print("welcome to ML")

welcome to ML


#0D array

In [3]:
import numpy as np
arr = np.array(42)
print(arr)


42


#1D ARRAY

In [4]:
import numpy as np
a = np.array([1,2,3])
print (a)


[1 2 3]


#2D ARRAY

In [18]:
import numpy as np
a=np.array([[1,2],[3,4]])
print (a)

[[1 2]
 [3 4]]


#3D ARRAY

In [20]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[1,5,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [1 5 9]]]


nDmin 

In [5]:
import numpy as np
arr=np.array([1,2],ndmin=6)
print(arr)

[[[[[[1 2]]]]]]


USING nDIM KEYWORD

In [8]:
a=np.array(42)
b=np.array([[1,2,3,4,5]],ndmin=9)
print(a.ndim)
print(b.ndim)

0
9


In [12]:
import numpy as npy
arrl=npy.array([1,3,5,7])
print(arrl.shape)

(4,)


In [1]:
import numpy as np
arr=np.zeros((1,2,3))
print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]]]


In [4]:
import numpy as np
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

print(np.sort(('c','a','d','b','g')))

[[2 3 4]
 [0 1 5]]
['a' 'b' 'c' 'd' 'g']


In [6]:
arr=np.array([1,2,3,4,5,6])
print(arr[0])


1


In [30]:
data=([1,2,3,4,5,6,7,8])
# data[1]
data[-7:-5]

[2, 3]

In [33]:
arr=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9],
            [10,11,12]]])
print(arr)
print("value",arr[0,3,2])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
value 12


In [36]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('last element from 2nd dim:',arr[1])

last element from 2nd dim: [ 6  7  8  9 10]


In [38]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:6:2])

[2 4 6]


In [40]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1:4])

[2 3 4]


In [42]:
arr = np.array([1,2,3,4,5,6,7,8])
x =np.where(arr%6==0)
print(x)


(array([5], dtype=int64),)


where

In [43]:
arr=np.array([1,2,3,40,5,40,40])
x=np.where(arr==40)
print(x)

(array([3, 5, 6], dtype=int64),)


SEARCHSORTED

In [50]:
arr=np.array([6,7,9,19])
x=np.searchsorted(arr,8)
print(x)
print(np.searchsorted([1,2,3,4,5],3))
print(np.searchsorted([1,2,3,4,5],3,side='right'))
np.searchsorted([1,2,3,4,5],[-10,10,2,3])


2
2
3


array([0, 5, 1, 2], dtype=int64)

RESHAPING ARRAY

In [51]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [52]:
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]
