In [6]:
print("welcome to ML")

welcome to ML


#0D array

In [7]:
import numpy as np
arr = np.array(42)
print(arr)


42


#1D ARRAY

In [8]:
import numpy as np
a = np.array([1,2,3])
print (a)


[1 2 3]


#2D ARRAY

In [9]:
import numpy as np
a=np.array([[1,2],[3,4]])
print (a)

[[1 2]
 [3 4]]


#3D ARRAY

In [10]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[1,5,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [1 5 9]]]


nDmin 

In [11]:
import numpy as np
arr=np.array([1,2],ndmin=6)
print(arr)

[[[[[[1 2]]]]]]


USING nDIM KEYWORD

In [12]:
a=np.array(42)
b=np.array([[1,2,3,4,5]],ndmin=9)
print(a.ndim)
print(b.ndim)

0
9


In [13]:
import numpy as npy
arrl=npy.array([1,3,5,7])
print(arrl.shape)

(4,)


In [14]:
import numpy as np
arr=np.zeros((1,2,3))
print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]]]


In [15]:
import numpy as np
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

print(np.sort(('c','a','d','b','g')))

[[2 3 4]
 [0 1 5]]
['a' 'b' 'c' 'd' 'g']


In [16]:
arr=np.array([1,2,3,4,5,6])
print(arr[0])


1


In [17]:
data=([1,2,3,4,5,6,7,8])
# data[1]
data[-7:-5]

[2, 3]

In [18]:
arr=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9],
            [10,11,12]]])
print(arr)
print("value",arr[0,3,2])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
value 12


In [19]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('last element from 2nd dim:',arr[1])

last element from 2nd dim: [ 6  7  8  9 10]


In [20]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:6:2])

[2 4 6]


In [21]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1:4])

[2 3 4]


In [22]:
arr = np.array([1,2,3,4,5,6,7,8])
x =np.where(arr%6==0)
print(x)


(array([5], dtype=int64),)


where

In [23]:
arr=np.array([1,2,3,40,5,40,40])
x=np.where(arr==40)
print(x)

(array([3, 5, 6], dtype=int64),)


SEARCHSORTED

In [24]:
arr=np.array([6,7,9,19])
x=np.searchsorted(arr,8)
print(x)
print(np.searchsorted([1,2,3,4,5],3))
print(np.searchsorted([1,2,3,4,5],3,side='right'))
np.searchsorted([1,2,3,4,5],[-10,10,2,3])


2
2
3


array([0, 5, 1, 2], dtype=int64)

RESHAPING ARRAY

In [25]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [45]:
np.dstack(a,)

array([[[0, 3],
        [1, 4],
        [2, 5]]])

In [3]:
import pandas as pd
a=pd.Series([10,20,30,40])
print(a)


0    10
1    20
2    30
3    40
dtype: int64


In [3]:
import pandas as pd

data=pd.read_json("C:/Users/User5/OneDrive/Desktop/ML/data.json")
print(data.to_string)

<bound method DataFrame.to_string of    Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300>
